spring:
  application:
    name: gateway-service
  profiles:
    active: local
  redis:
    password:
    host: 172.16.3.52
    database: 1
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      - id: wjy-product            #产品服务
        uri: lb://wjy-product
        predicates:
        - Path=/product/**
        filters:
        - TokenFilter
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10 #允许用户每秒处理多少个请求
            redis-rate-limiter.burstCapacity: 20 #令牌桶的容量，允许在一秒钟内完成的最大请求数
          # 降级配置
        - name: Hystrix
          args:
            name: default
      - id: rtc-store             #门店端
        uri: lb://rtc-store
        predicates:
        - Path=/store/**
        filters:
        - TokenFilter
      - id: rtc-doctor             #医生端
        uri: lb://rtc-doctor
        predicates:
        - Path=/doctor/**
        filters:
        - TokenFilter
server:
  port: 20003


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/

feign:
  hystrix:
    enabled: true


---
##########################################################
###################  本地环境的profile  ###################
##########################################################
spring:
  profiles: local
#单点登录配置
sso-server:
  app-id: 1002
  api-host: http://172.16.3.52:8888   # sso-api 接口地址
  sign-key: A82E19010F2EF292137EB0D84A500FDC

---
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
#单点登录配置
sso-server:
  app-id: 1002
  api-host: http://172.16.3.52:8888   # sso-api 接口地址
  sign-key: A82E19010F2EF292137EB0D84A500FDC

---
##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
#单点登录配置
sso-server:
  app-id: 1002
  api-host: http://172.16.3.52:8888   # sso-api 接口地址
  sign-key: A82E19010F2EF292137EB0D84A500FDC